### ISSUE TITLE
Adding a block on enter

### ISSUE THREAD

**Issue by bph** [WordPress/developer-blog-content#26]
Also, a pre-editorial group article used for testing on the site, and that is ready for review now. 
[The public preview](https://developer.wordpress.org/news/?p=30&preview=1&_ppp=e1a8ef0057)

**Comment by bph** [comment]
@dsas when you go over the post again, consider also revising the Title, see the [comment from the meeting](https://wordpress.slack.com/archives/C03RL47B3S8/p1669901634125889). 
![Screen Shot 2022-12-13 at 08 36 46](https://user-images.githubusercontent.com/39980/207338147-50230977-3137-4549-a0a4-a6f56ab2ff45.png)

**Comment by dsas** [comment]
Ok, I'll try to think of something better 👍

**Comment by dsas** [comment]
I've retitled to "Splitting and merging blocks" and made some other improvements to the text and code samples. I'd be grateful if someone could give this a read through and ensure it makes sense.

**Comment by marybaum** [comment]
Happy to! Heading for my keyboard now.I might have some ideas for headlines and subheads—I am a shameless direct marketer 😜... from my phoneOn Jan 16, 2023, at 8:24 AM, Dean Sas ***@***.***> wrote:﻿
I've retitled to "Splitting and merging blocks" and made some other improvements to the text and code samples. I'd be grateful if someone could give this a read through and ensure it makes sense.

**Comment by marybaum** [comment]
Done! Did my copy edit and added a new headline. Let me know what yall think!

**Comment by dsas** [comment]
Wow thanks @marybaum that certainly is a lot more engaging. I've made some very small changes to ensure it's still technically accurate.

The only bone of contention is the subheading:
> If you can split and merge blocks, you can make them happen too. 

I'm not 100% clear on what it means :) To me it reads like "If you can split and merge blocks, you can make blocks happen too".

**Comment by marybaum** [comment]
Oh man. Let me revisit that! I think that’s an autocorrect I missed! New adhd meds arrive on the 21st. Until then, the forecast is for periods of brainlessness.🎵sings🎵Eleanor Rigby/she keeps her face in a jar by the door/I have ADHD/I keep my brains in the ki-it-tchen drawer/😜... from my phoneOn Jan 16, 2023, at 2:28 PM, Dean Sas ***@***.***> wrote:﻿
Wow thanks @marybaum that certainly is a lot more engaging. I've made some very small changes to ensure it's still technically accurate.
The only bone of contention is the subheading:

If you can split and merge blocks, you can make them happen too.

I'm not 100% clear on what it means :) To me it reads like "If you can split and merge blocks, you can make blocks happen too".

**Comment by marybaum** [comment]
Done! Subhead is a little more clear now.

**Comment by dsas** [comment]
> If you can split and merge blocks, you can make those cool things happen on your site

I don't want to block based on this but honestly I'm still not keen. If you can already split and merge blocks where else are you doing it but your site?

I don't know if "splitting and merging" wording is a good angle. Will people already understand that enough to want to read the article? Being pedantic but the title is about hitting enter but that only splits not merges.

I've spent a while thinking about it and can't think up anything I'm happy with either. I'm leaning towards omitting the sub-headline and going straight into that strong opening narrative you added.

**Comment by marybaum** [comment]
Love it! I think that's great—let's lose the subhead, then!

**Comment by dsas** [comment]
Done 👍 I think this is good to go from my point of view.

**Comment by bph** [comment]
@marybaum if you get a moment could you double-check on our Pre-publishing checklist for this post.

- [ ] Post Title in Sentence case
- [ ] Are Category or Categories selected?
- [ ]  Are Tags identifies?
- [ ]  Is there an Excerpt?
- [ ]  Props added?

If all is done, please Publish! 🛳️

**Comment by marybaum** [comment]
Published!



 Mary Baum
314.609.7844

Twitter <http://twitter.com/marybaum>
Github <http://github.com/marybaum>
WordPress <https://profiles.wordpress.org/marybaum/>
Speaking <https://wordpress.tv/speakers/mary-baum/>

**Comment by bph** [comment]
[Some very cool things can happen when you hit Enter in a block.](https://developer.wordpress.org/news/2023/01/some-very-cool-things-can-happen-when-you-hit-enter-in-a-block/)
